### ISSUE TITLE
Prototipo de Realidad Aumentada

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-team-pc-box#2]
[Práctica prototipo RA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-team-pc-box/files/8120241/Practica.prototipo.RA.pdf)

**Comment by claudiasilvavenda** [comment]
El prototipo esta completo.
la calif. es 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
